export const ASYNC_FETCH_POPULAR_SHOWS_REQUEST =
  "ASYNC_FETCH_POPULAR_SHOWS_REQUEST";
export const ASYNC_FETCH_POPULAR_SHOWS_SUCCESS =
  "ASYNC_FETCH_POPULAR_SHOWS_SUCCESS";
export const ASYNC_FETCH_POPULAR_SHOWS_ERROR =
  "ASYNC_FETCH_POPULAR_SHOWS_ERROR";

export const ASYNC_FETCH_SHOW_REQUEST = "ASYNC_FETCH_SHOW_REQUEST";
export const ASYNC_FETCH_SHOW_SUCCESS = "ASYNC_FETCH_SHOW_SUCCESS";
export const ASYNC_FETCH_SHOW_ERROR = "ASYNC_FETCH_SHOW_ERROR";

export const ASYNC_FETCH_TRAILER_REQUEST = "ASYNC_FETCH_TRAILER_REQUEST";
export const ASYNC_FETCH_TRAILER_SUCCESS = "ASYNC_FETCH_TRAILER_SUCCESS";
export const ASYNC_FETCH_TRAILER_ERROR = "ASYNC_FETCH_TRAILER_ERROR";
